MVP, Current website UI. Working page jumps, added info, add buttons.
BlessP/Step pull request #3
Opened 2020-06-09 19:59 UTC by BlessP

This is the basic MVP. Features an about and experience section along with a contact page. Working buttons that jump throughout the page.

2020-06-09 20:06 UTC, jbiral requested changes
Looks good! Could you attach a screenshot of what hte page looks like in the PR description? Thanks!

2020-06-09 20:06 UTC, jbir789 commented on portfolio/src/main/webapp/index.html
> +     <p class="wordtext">My name is <b>Bless Paynes </b>and I'm a junior currently attending <b>Hampton University</b>. I've lived in <b>Northern VA </b> my entire life but I have travelled a ton in
nit: remove the space after Paynes and add it after the `</b>` tag

2020-06-09 20:06 UTC, jbir789 commented on portfolio/src/main/webapp/index.html
> +     <h1> Contact Me</h1>
nit: make sure you don't have blank spaces after the opening tag

2020-06-09 20:06 UTC, jbir789 commented on portfolio/src/main/webapp/index.html
> +     <p style="color:purple;"> Bpaynes4291@gmail.com</p>
nit: make sure you don't have blank spaces after the opening tag

2020-06-09 21:02 UTC, jbiral requested changes

2020-06-09 21:02 UTC, jbiral commented on portfolio/src/main/webapp/index.html
> -     <h1> Experience</h1>
Since you removed the Experience title, it's no longer showing up in your page. Is that intended?

Alternatively, you could try to do:

```
<h2 id="Experience">Experience</h2>
```

Which should be sufficient for the above links to jump to this title (without needing the `<a>` tag)

2020-06-09 21:02 UTC, jbiral commented on portfolio/src/main/webapp/index.html
> +     <h1>Contact Me</h1>
Typically, `<h2>` is preferred for titles that aren't the page title

2020-06-09 21:02 UTC, jbiral commented on portfolio/src/main/webapp/index.html
> +        <h1>2x Google STEP (Previously known as EP) Intern</h1>
You can use h3 here, and then `<ul><li>Your item</li></ul>` for the bullet points below, what do you think?

2020-06-09 21:05 UTC, BlessP commented on portfolio/src/main/webapp/index.html
> +        <h1>2x Google STEP (Previously known as EP) Intern</h1>
Okay understandable, do you know of a way I can adjust either the distance between the bullet and content or possibly remove them?

2020-06-09 21:32 UTC, jbir789 commented on portfolio/src/main/webapp/index.html
> +        <h1>2x Google STEP (Previously known as EP) Intern</h1>
You can add a padding / margin in the css: https://stackoverflow.com/questions/19254411/how-do-i-set-vertical-space-between-list-items/19254441

2020-06-10 00:06 UTC, ginellegaisano commented on portfolio/src/main/webapp/index.html
> +        <li>Worked on Android App team
missing "li" closing tag.

2020-06-10 16:29 UTC, jbiral approved these changes

2020-06-10 16:33 UTC, ginellegaisano approved these changes

2020-06-10 16:38 UTC, merged